# Generated by Django 6.0.4 on 2026-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='experiencia',
            field=models.TextField(blank=True),
        ),
    ]
