# Generated by Django 6.0.4 on 2026-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video_banner',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
